name: commerciosdk
description: Pure Dart library allowing you to easily integrate with the Commercio.network blockchain
version: 0.1.3
author: Commercio.network <developer@commercio.network>
homepage: https://github.com/commercionetwork/sdk.dart
documentation: https://dart.sdk.docs.commercio.network

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.7
  hex: ^0.1.2
  http: ^0.12.0
  equatable: ^1.0.1
  json_annotation: ^3.0.0
  uuid: ^2.0.2
  asn1lib: ^0.5.13

  # Crypto utils
  # sacco: ^0.1.2
  sacco:
    path: ..\sacco.dart
  encrypt: ^3.3.1
  ed25519_hd_key: ^1.0.1
  pem: ^1.0.0
  pointycastle: ^1.0.1


dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.9+1
  json_serializable: ^3.2.0
  test: ^1.9.3
