name: commerciosdk
description: Pure Dart library allowing you to easily integrate with the Commercio.network blockchain
version: 2.1.3-pre.1
homepage: https://github.com/commercionetwork/sdk.dart
documentation: https://dart.sdk.docs.commercio.network

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.2.3
  hex: ^0.1.2
  http: ^0.12.0
  equatable: ^1.0.1
  json_annotation: ^3.0.1
  uuid: ^2.2.2
  asn1lib: ^0.6.5
  basic_utils: ^2.5.3

  # Crypto utils
  sacco: ^0.1.5
  encrypt: ^4.0.3
  ed25519_hd_key: 1.0.1
  pointycastle: ^1.0.2
  steel_crypt: ^1.7.1+1


dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.9+1
  collection: ^1.14.13
  json_serializable: ^3.2.0
  mockito: ^4.1.4
  pedantic: ^1.9.2
  test: ^1.15.7
  test_coverage: ^0.5.0
