name: commerciosdk
description: Pure Dart library allowing you to easily integrate with the Commercio.network blockchain
version: 0.0.1
author: Commercio.network <commerciosrl@gmail.com>
homepage: https://github.com/commercionetwork/sdk.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.7
  hex: ^0.1.2
  http: ^0.12.0
  equatable: ^0.5.0

  # Crypto utils
  sacco: ^0.0.9
  encrypt: ^3.3.1

dev_dependencies:
  test: ^1.6.8